name: Build Docker image

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ml-fastapi
  IMAGE_TAG: ${{github.ref_name}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/alfranz/ml-fastapi:latest
          docker build . --tag ghcr.io/alfranz/ml-fastapi:${{ env.IMAGE_TAG }}
          docker push ghcr.io/alfranz/ml-fastapi:latest
          docker push ghcr.io/alfranz/ml-fastapi:${{ env.IMAGE_TAG }}
